name: Create Issue
on:
  push:
    branches: [ main ]
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create a new issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'New Issue from Workflow',
              body: 'This issue was created automatically by GitHub Actions.'
            });
